const Map<String, List<String>> morphCategoriesAndLabels = {
  "Pos": [
    "ADJ",
    "ADP",
    "ADV",
    "AFFIX",
    "AUX",
    "CCONJ",
    "DET",
    "INTJ",
    "NOUN",
    "NUM",
    "PART",
    "PRON",
    "PROPN",
    "PUNCT",
    "SCONJ",
    "SPACE",
    "SYM",
    "VERB",
    "X",
  ],
  "AdvType": ["Adverbial", "Tim"],
  "Aspect": [
    "Imp",
    "Perf",
    "Prog",
    "Hab",
  ],
  "Case": [
    "Nom",
    "Acc",
    "Dat",
    "Gen",
    "Voc",
    "Abl",
    "Loc",
    "All",
    "Ins",
    "Ess",
    "Tra",
    "Com",
    "Par",
    "Adv",
    "Ref",
    "Rel",
    "Equ",
    "Dis",
    "Abs",
    "Erg",
    "Cau",
    "Ben",
    "Sub",
    "Sup",
    "Tem",
    "Obl",
    "Acc,Dat",
    "Acc,Nom",
    "Pre",
  ],
  "ConjType": ["Coord", "Sub", "Cmp"],
  "Definite": ["Def", "Ind", "Cons"],
  "Degree": [
    "Pos",
    "Cmp",
    "Sup",
    "Abs",
  ],
  "Evident": ["Fh", "Nfh"],
  "Foreign": ["Yes"],
  "Gender": ["Masc", "Fem", "Neut", "Com"],
  "Mood": [
    "Ind",
    "Imp",
    "Sub",
    "Cnd",
    "Opt",
    "Jus",
    "Adm",
    "Des",
    "Nec",
    "Pot",
    "Prp",
    "Qot",
    "Int",
  ],
  "NounType": ["Prop", "Comm", "Not_proper"],
  "NumForm": [
    "Digit",
    "Word",
    "Roman",
    "Letter",
  ],
  "NumType": [
    "Card",
    "Ord",
    "Mult",
    "Frac",
    "Sets",
    "Range",
    "Dist",
  ],
  "Number": [
    "Sing",
    "Plur",
    "Dual",
    "Tri",
    "Pauc",
    "Grpa",
    "Grpl",
    "Inv",
  ],
  "Number[psor]": ["Sing", "Plur", "Dual"],
  "Person": [
    "0",
    "1",
    "2",
    "3",
    "4",
  ],
  "Polarity": ["Pos", "Neg"],
  "Polite": ["Infm", "Form", "Elev", "Humb"],
  "Poss": ["Yes"],
  "PrepCase": ["Npr"],
  "PronType": [
    "Prs",
    "Int",
    "Rel",
    "Dem",
    "Tot",
    "Neg",
    "Art",
    "Emp",
    "Exc",
    "Ind",
    "Rcp",
    "Int,Rel",
  ],
  "PunctSide": ["Ini", "Fin"],
  "PunctType": [
    "Brck",
    "Dash",
    "Excl",
    "Peri",
    "Qest",
    "Quot",
    "Semi",
    "Colo",
    "Comm",
  ],
  "Reflex": ["Yes"],
  "Tense": ["Pres", "Past", "Fut", "Imp", "Pqp", "Aor", "Eps", "Prosp"],
  "VerbForm": [
    "Fin",
    "Inf",
    "Sup",
    "Part",
    "Conv",
    "Vnoun",
    "Ger",
    "Adn",
    "Lng",
  ],
  "VerbType": ["Mod", "Caus"],
  "Voice": ["Act", "Mid", "Pass", "Antip", "Cau", "Dir", "Inv", "Rcp", "Caus"],
  "X": ["X"],
};
