name: 🐛 Bug report
description: Create a report to help us improve
labels: bug
body:
  - type: textarea
    id: bug-description
    attributes:
      label: "Bug Description"
      description: "A clear and concise description of what the bug is. Please add screenshots if you have as they usually help us a lot."
      placeholder: "Describe the bug here..."
    validations:
      required: true
  - type: textarea
    id: reproduce-steps
    attributes:
      label: "Steps to Reproduce"
      description: "Steps to reproduce the behavior:"
      placeholder: "1. Go to '...'\n2. Click on '...'\n3. Scroll down to '...'\n4. See error"
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: "Expected Behavior"
      description: "A clear and concise description of what you expected to happen."
      placeholder: "Describe what you expected to happen here..."
    validations:
      required: true
  - type: input
    id: app-version
    attributes:
      label: "App Version"
      description: "Please provide the version of the app you are using."
      placeholder: "e.g. 1.12.0"
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: "Platform"
      description: "Select the platform where the bug occurs."
      options:
        - Android (PlayStore)
        - Android (F-Droid)
        - Android (Other)
        - iOS (iPhone)
        - iOS (iPad)
        - Web (Chrome(ium))
        - Web (Firefox)
        - Web (Safari)
        - Linux (Snap)
        - Linux (Flatpak)
        - Linux (Other)
        - macOS (iOS/iPadOS version)
        - macOS (Self-compiled)
        - Windows (Self-compiled)
    validations:
      required: true
  - type: input
    id: platform-info
    attributes:
      label: "Additional Platform Information"
      description: "Please provide the following information:"
      placeholder: "Device: [e.g. iPhone6, PC, Pixel 3]\nOS: [e.g. iOS, Android, Windows, Linux, macOS]\nBrowser (if applicable): [e.g. Chrome, Safari]"
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: "Additional Context"
      description: "Add any other context about the problem here."
    validations:
      required: false
