// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3B9OSBjVluEPl0DWMqXa4zwjWLPAJf6E',
    appId: '1:983546383265:web:183aaecc08ea18c204d9e0',
    messagingSenderId: '983546383265',
    projectId: 'gov-chat-7a710',
    authDomain: 'gov-chat-7a710.firebaseapp.com',
    storageBucket: 'gov-chat-7a710.firebasestorage.app',
    measurementId: 'G-G8Q24S8H43',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMMxbAVCBWivY_3R9eo4CjdWYEvnJ__ek',
    appId: '1:983546383265:android:3160fc7d2348d6e704d9e0',
    messagingSenderId: '983546383265',
    projectId: 'gov-chat-7a710',
    storageBucket: 'gov-chat-7a710.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE3dC4dT0k4NqhxnSCjbGfSKWn5hJurlQ',
    appId: '1:983546383265:ios:0caf1f4fe354add104d9e0',
    messagingSenderId: '983546383265',
    projectId: 'gov-chat-7a710',
    storageBucket: 'gov-chat-7a710.firebasestorage.app',
    iosBundleId: 'im.fluffychat.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCE3dC4dT0k4NqhxnSCjbGfSKWn5hJurlQ',
    appId: '1:983546383265:ios:b902bcd0b0546e7c04d9e0',
    messagingSenderId: '983546383265',
    projectId: 'gov-chat-7a710',
    storageBucket: 'gov-chat-7a710.firebasestorage.app',
    iosBundleId: 'im.fluffychat.fluffychat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3B9OSBjVluEPl0DWMqXa4zwjWLPAJf6E',
    appId: '1:983546383265:web:c5837ba7ac8d6cb704d9e0',
    messagingSenderId: '983546383265',
    projectId: 'gov-chat-7a710',
    authDomain: 'gov-chat-7a710.firebaseapp.com',
    storageBucket: 'gov-chat-7a710.firebasestorage.app',
    measurementId: 'G-4KQT3T343M',
  );
}
