// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXK_jobz9YjNmiS1leA-vbGd_a8W-TCGI',
    appId: '1:545984292675:web:80f3babc12328eddb931f6',
    messagingSenderId: '545984292675',
    projectId: 'pangea-chat-936ee',
    authDomain: 'pangea-chat-936ee.firebaseapp.com',
    databaseURL: 'https://pangea-chat-936ee-default-rtdb.firebaseio.com',
    storageBucket: 'pangea-chat-936ee.firebasestorage.com',
    measurementId: 'G-FKP13VDEBX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyWBbl83WXzbVr6txyCmlUsZhpWomQfdg',
    appId: '1:545984292675:android:d808acce7a80c20bb931f6',
    messagingSenderId: '545984292675',
    projectId: 'pangea-chat-936ee',
    databaseURL: 'https://pangea-chat-936ee-default-rtdb.firebaseio.com',
    storageBucket: 'pangea-chat-936ee.firebasestorage.com',
    androidClientId:
        '545984292675-2amsnoan1mt6lec1fld1a7eagu6gej7o.apps.googleusercontent.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl8QZd9_PnaqJY2zLHCwlsmSWdq7hnH-U',
    appId: '1:545984292675:ios:1226406ecc36e056b931f6',
    messagingSenderId: '545984292675',
    projectId: 'pangea-chat-936ee',
    databaseURL: 'https://pangea-chat-936ee-default-rtdb.firebaseio.com',
    storageBucket: 'pangea-chat-936ee.firebasestorage.com',
    iosClientId:
        '545984292675-f5p76l3h9sibsonrct7a8l9ca3c69at0.apps.googleusercontent.com',
    iosBundleId: 'com.talktolearn.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCl8QZd9_PnaqJY2zLHCwlsmSWdq7hnH-U',
    appId: '1:545984292675:ios:1226406ecc36e056b931f6',
    messagingSenderId: '545984292675',
    projectId: 'pangea-chat-936ee',
    databaseURL: 'https://pangea-chat-936ee-default-rtdb.firebaseio.com',
    storageBucket: 'pangea-chat-936ee.firebasestorage.com',
    iosClientId:
        '545984292675-f5p76l3h9sibsonrct7a8l9ca3c69at0.apps.googleusercontent.com',
    iosBundleId: 'com.talktolearn.chat',
  );
}
